# -*- coding: utf-8 -*-
"""시각화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIsrVRExb2Y17gBEOYzknxW4F7DPq8Zp
"""


import pandas as pd
import folium
from streamlit_folium import st_folium
import streamlit as st

# 페이지 설정
st.set_page_config(layout="wide")

# 데이터 불러오기
df = pd.read_csv("map.csv")
df = df.dropna(subset=['위도', '경도'])

# 시군구 추출
def extract_city(addr):
    try:
        return addr.split()[1]
    except:
        return None

df['시군구'] = df['소재지(사업장)'].apply(extract_city)

# 소재지 선택
소재지들 = ['전체'] + sorted(df['소재지'].dropna().unique())
선택_소재지 = st.selectbox("소재지 선택", 소재지들)

# 시군구 필터
if 선택_소재지 == '전체':
    선택_데이터 = df.copy()
    시군구 = None
else:
    선택_데이터 = df[df['소재지'] == 선택_소재지]
    시군구들 = sorted(선택_데이터['시군구'].dropna().unique())
    선택_시군구 = st.selectbox("시/군/구 선택", 시군구들)
    선택_데이터 = 선택_데이터[선택_데이터['시군구'] == 선택_시군구]

# 지도 만들기
center_lat = 선택_데이터['위도'].mean()
center_lon = 선택_데이터['경도'].mean()
m = folium.Map(location=[center_lat, center_lon], zoom_start=6 if 선택_소재지 == '전체' else 11)

for _, row in 선택_데이터.iterrows():
    folium.Marker(
        location=[row['위도'], row['경도']],
        popup=f"{row['사업장명']}<br>체불액: {row['체불액(원)']}",
        tooltip=row['사업장명']
    ).add_to(m)

# 지도 표시
st_folium(m, width=1000, height=600)

# 표 표시
st.markdown("### 📋 사업장 목록")
st.dataframe(선택_데이터[['사업장명', '주소지(사업주)', '체불액(원)', '소재지', '시군구']].reset_index(drop=True))
